// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcgegfycdrqlmflboymx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjZ2VnZnljZHJxbG1mbGJveW14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTkyMTQsImV4cCI6MjA2NzQ3NTIxNH0.sFPPFISLdGtNtPtHsSnte5oU4yi1EOm9Om9HqIz-7cQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});